myapp/urls.py
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    # path(r'', views.index, name='index'),
    path(r'about/', views.about, name='about'),
    # path(r'<int:book_id>/', views.details, name='details'),
    path(r'findbooks/', views.findbooks, name='findbooks'),
    path(r'place_order/', views.place_order, name='place_order'),
    path(r'review/', views.review_view, name='review'),
    path(r'login/', views.user_login, name='user_login'),
    path(r'logout/', views.user_logout, name='user_logout'),
    path(r'check_reviews/<int:book_id>',views.chk_reviews, name='check_reviews'),
    path(r'register/',views.user_register,name='user_register'),
    path(r'forget/', views.forget, name='forget'),
    path(r'', views.IndexView.as_view(), name='index'),
    path(r'<int:pk>/', views.MyDetailView.as_view(), name='details'),

]

mysiteF19/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'myapp/', include('myapp.urls')),
    #path(r'myapp/', include('myapp.urls1')),
    #path(r'/about/', include('myapp.urls1')),
    #path(r'<int:book_id>/', include('myapp.urls1')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

myapp/models.py
from django.db import models
import random
import datetime
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator
import os
from django.conf import settings
from django.utils.safestring import mark_safe


class Publisher(models.Model):
    name = models.CharField(max_length=200)
    website = models.URLField()
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, default='USA')
    def __str__(self):
        return self.name

class Book(models.Model):
    CATEGORY_CHOICES = [
        ('S', 'Scinece&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    title = models.CharField(max_length=200)
    category = models.CharField(max_length=1, choices=CATEGORY_CHOICES, default='S')
    num_pages = models.PositiveIntegerField(default=100)
    price = models.DecimalField(max_digits=10, decimal_places=2,validators=[MaxValueValidator(1000), MinValueValidator(0)])
    publisher = models.ForeignKey(Publisher, related_name='books', on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    num_reviews = models.PositiveIntegerField(default=0)
    def __str__(self):
        return self.title

class Member(User):
    STATUS_CHOICES = [
        (1, 'Regular member'),
        (2, 'Premium Member'),
        (3, 'Guest Member'),
    ]

    status = models.IntegerField(choices=STATUS_CHOICES, default=1)
    address = models.CharField(max_length=300, blank=True)
    city = models.CharField(max_length=20, default='Windsor')
    province = models.CharField(max_length=2, default='ON')
    last_renewal = models.DateField(default=timezone.now)
    auto_renew = models.BooleanField(default=True)
    borrowed_books = models.ManyToManyField(Book, blank=True)
    image = models.ImageField(upload_to='media', blank=True)
    externalURL = models.URLField(blank=True)

    def url(self):

        if self.externalURL:
            return self.externalURL
        else:

            return os.path.join('/', settings.MEDIA_URL, os.path.basename(str(self.image)))

    def image_tag(self):

        return mark_safe('<img src="{}" width="150" height="150" />'.format(self.url()))

    image_tag.short_description = 'Image'




    def url(self):
        # returns a URL for either internal stored or external image url
        if self.externalURL:
            return self.externalURL
        else:
            # is this the best way to do this??
            return os.path.join('/', settings.MEDIA_URL, os.path.basename(str(self.image)))

    def image_tag(self):
        # used in the admin site model as a "thumbnail"
        return mark_safe('<img src="{}" width="50" height="50" />'.format(self.url()))

    image_tag.short_description = 'Image'

class Order(models.Model):
    ORDER_CHOICES = [
        (0, 'Purchase'),
        (1, 'Borrow')
    ]
    books = models.ManyToManyField(Book)
    member = models.ForeignKey(Member, on_delete=models.CASCADE, related_name='books')
    order_type = models.IntegerField(choices=ORDER_CHOICES, default=1)
    order_date = models.DateField(default=timezone.now)
    def __str__(self):
        return str(self.id)

    def total_items(self):
        return self.books.count()

class Review(models.Model):
    reviewer = models.EmailField()
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    rating = models.PositiveIntegerField()
    comments = models.TextField(blank=True)
    date = models.DateField(default=timezone.now)
    def __str__(self):
        return str(self.id)

myapp/forms.py
from django import forms
from myapp.models import Order, Review, Member

class SearchForm(forms.Form):
    CATEGORY_CHOICES = [
        ('S', 'Scinece&Tech'),
        ('F', 'Fiction'),
        ('B', 'Biography'),
        ('T', 'Travel'),
        ('O', 'Other')
    ]
    name = forms.CharField(max_length=100, required=False, label='Your name')
    category = forms.ChoiceField(widget=forms.RadioSelect,choices = CATEGORY_CHOICES, required=False, label='Select a category')
    max_price = forms.IntegerField(label='Maximum Price', min_value=0, required=True)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['books', 'member', 'order_type']
        widgets = {'books': forms.CheckboxSelectMultiple(), 'order_type':forms.RadioSelect}
        labels = {'member': u'Member name', }

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ['reviewer', 'book', 'comments', 'rating']
        widgets = {'book': forms.RadioSelect()}
        labels = {
            'reviewer': u'Please enter a valid email',
            'rating': u'Rating: An integer between 1 (worst) and 5 (best)'
        }

class MemberForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = Member
        fields = ['first_name', 'last_name', 'email', 'username', 'status', 'address', 'city', 'province']
        widgets = {'address': forms.Textarea(attrs={'rows': 2})}

    def clean(self):
        cleaned_data = super().clean()
        passw = cleaned_data['password']

myapp/views.py
import string

from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect, reverse
from .models import Publisher, Book, Member, Order
from .forms import SearchForm, OrderForm, ReviewForm, MemberForm
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout, hashers
from django.contrib.auth.decorators import login_required
from django.db.models import Avg, Q
from random import randint
from django.views.generic import *
import random

from datetime import  datetime


class IndexView(ListView):
    model = Book
    template_name = 'myapp/index.html'


class MyDetailView(DetailView):
    model = Book
    template_name = 'myapp/detail.html'
# def index(request):
#     booklist = Book.objects.all().order_by('id')[:10]
#     return render(request, 'myapp/index.html', {'booklist': booklist})

def about(request):
    # return render(request, 'myapp/about.html')
    lucky_num = request.COOKIES.get('lucky_num')
    if lucky_num is None:
        lucky_num = randint(1, 100)
    resp = render(request, 'myapp/about.html', {'lucky_num': lucky_num})
    resp.set_cookie('lucky_num', lucky_num, max_age=60 * 5)
    return resp


# def details(request, book_id):
#
#     book = get_object_or_404(Book, pk=book_id)
#     return render(request, 'myapp/detail.html', {'book': book})
# Create your views here.

def findbooks(request):
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            name = form.cleaned_data['name']
            category = form.cleaned_data['category']
            max_price = form.cleaned_data['max_price']

            booklist = Book.objects.filter(price__lte=max_price)

            if category:
                booklist = booklist.filter(category=category)
            return render(request, 'myapp/results.html', {'booklist':booklist, 'name':name, 'category':category})


        else:
            return HttpResponse('Invalid data')
    else:
        form = SearchForm()
        return render(request, 'myapp/findbooks.html', {'form':form})

def place_order(request):
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            books = form.cleaned_data['books']
            order = form.save(commit=False)
            member = order.member
            type = order.order_type
            order.save()
            order.books.set(books)

            if type == 1:
                for b in order.books.all():
                    member.borrowed_books.add(b)
            return render(request, 'myapp/order_response.html', {'books': books, 'order':order})
        else:
            return render(request, 'myapp/placeorder.html', {'form':form})

    else:
        form = OrderForm()
        return render(request, 'myapp/placeorder.html', {'form':form})



def review_view(request):
    member = Member.objects.filter(username=request.user.username).first()
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if member.status ==1 or member.status==2:

            if form.is_valid():
                rating = form.cleaned_data['rating']
                book = form.cleaned_data['book']
                if rating > 5 or rating < 1:
                    return HttpResponse('You must enter a rating between 1 and 5!')
                else:
                    review = form.save()
                    book.num_reviews+= 1
                    book.save()
                    return redirect('myapp:index')
            else:
                return render(request, 'myapp/review.html', {'form':form})
        else:
            return render(request, 'myapp/Guest.html', {'error': 'Guest login not allowed ', 'member': member})


    else:
        form = ReviewForm()
        return render(request, 'myapp/review.html', {'form':form})

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['last_login'] = str(datetime.now())
                request.session.set_expiry(60 * 60)
                request.session.save()
                if 'login' not in request.META['HTTP_REFERER']:
                    respLogin = HttpResponseRedirect(request.META['HTTP_REFERER'])
                else:
                    respLogin = HttpResponseRedirect(reverse('myapp:index'))

                return respLogin
                # return HttpResponseRedirect(reverse('myApp:index'))
            else:
                return HttpResponse('Your account is disabled.')
        else:
            return HttpResponse('Invalid login details.')
    else:
        return render(request, 'myapp/login.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse(('myapp:index')))

def chk_reviews(request, book_id):
    book = Book.objects.get(id=book_id)
    member = Member.objects.filter(username=request.user.username).first()
    if request.user.is_authenticated and member is not None:
        if member.status == 1 or member.status == 2:
            reviews = book.review_set
            rating = reviews.aggregate(Avg('rating'))['rating__avg']
            return render(request, 'myapp/chk_reviews.html', {'rating': rating, 'book': book})
        else:
            return render(request, 'myapp/Guest.html', {'error': 'Guest user cant view reviews ', 'book': book})
    else:
        return render(request, 'myapp/login.html', {'error': 'You are not a registered member!', 'book': book})

def user_register(request):
    if request.method == 'POST':
        form = MemberForm(request.POST)
        if form.is_valid():
            member = form.save(commit=False)
            member.password = hashers.make_password(form.cleaned_data['password'])
            member.save()
            request.session['register_success'] = True
            resp = HttpResponseRedirect(reverse('myapp:user_login'))
            return resp
        else:
            return render(request, 'myapp/register.html', {'form': form})
    else:
        form = MemberForm()
        return render(request, 'myapp/register.html', {'form': form})



def forget(request):
    # if request.user.is_authenticated:
    #     return redirect(reverse('myApp:index'))
    password_reset_not_found = password_reset_success = False
    if request.method == 'POST':
        username = request.POST['username']
        user = User.objects.filter(Q(username=username) or Q(email=username)).first()
        if user:
            letters = string.ascii_lowercase
            password = ''.join(random.choice(letters) for x in range(6))
            user.password = hashers.make_password(password)

            subject = 'PASSWORD RESET REQUEST FORM eBook'
            message = ' PLEASE RESET YOUR PASSWORD ---->' + password
            email_from = settings.EMAIL_HOST_USER
            recipient_list = ['keshapatel41096@gmail.com', ]
            send_mail(subject, message, email_from, recipient_list)

            user.save()

            # password_reset_success = True
        else:
            return HttpResponse('USER NOT FOUND !')
        request.session.save()
        return render(request, 'myapp/Emailsent.html', )

    else:
        return render(request, 'myapp/Forgot.html')

z

myapp/templates/myapp/Emailsent.html
{% extends 'myapp/base.html' %}

{% block title %}
    Sent!
{% endblock %}
<h1>RESENT EMAIL HAS BEEN SEND</h1>
{% block body_block %}
    <h1>RESET EMAIL HAS BEEN SEND</h1>
<a href="{% url 'myapp:user_login' %}">Back Namespacing</a>

{% endblock %}

myapp/templates/myapp/Forgot.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:forget' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        Enter Username: <input type="text" name="username"  /><br><br>
        <input type="submit" value="Forget">

    </form>

{% endblock %}

myapp/templates/myapp/about.html
{% extends 'myapp/base.html' %}

{% block title %}
    eBook APP About page
{% endblock %}

{% block body_block %}
    {% include 'myapp/about0.html' %}
{% endblock %}

{% block myhdg %}
    Hi Kesha
{% endblock %}

myapp/templates/myapp/about0.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>ebook APP</title>
</head>
<body>
    <h1>This is an ebook APP</h1>
    <h3>Your lucky number is {{ lucky_num }}</h3>

<br />
{#    <a href="/myapp">link for index page</a>#}
{#    <a href="{% url 'myapp:index' %}">index</a>#}

</body>
</html>

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load staticfiles %}

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<html>
<head>
<link rel="stylesheet" type="text/css" href="{% static 'myapp/style.css' %}" />
<title>eBook APP - {% block title %}Welcome!{% endblock %}</title>
</head>

<body>
<div>
<h1>{% block myhdg %}Hello
    {% if request.user.is_authenticated %}
        {{ request.user.username}}
        {% else %}
    User !
    {% endif %}
 {% endblock %}</h1>
            {% block body_block%}*** {% endblock %}
</div>
{% if request.user.is_authenticated %}
        <hr />
            {% if request.session.last_login %}
                Your last login was {{ request.session.last_login }}
            {% else %}
                Your last login was more than one hour ago
            {% endif %}
        {% endif %}
        <hr/>
<hr>
    {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:user_logout' %}">Logout</a>
      </li>
    {% else %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:user_login' %}">Login</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'myapp:user_register' %}">Register</a>
      </li>
    {% endif %}
<div>
<ul>
<li class="hbar1"><a href="/myapp/about">Find out about this site</a></li>
<li class="hbar1"><a href = "{% url 'myapp:index' %}">Click here to return to main page</a></li>
    <li class="hbar1"><a href="{%  url 'myapp:place_order' %}">Place order</a></li>
    <li class="hbar1"><a href = "{% url 'myapp:findbooks' %}">Click here to find the books</a></li>
</ul>
</div>
</body>
</html>

myapp/templates/myapp/chk_reviews.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <h5>Average Rating: {{ rating }}</h5>
{% endblock %}

myapp/templates/myapp/detail.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% include 'myapp/detail0.html' %}
{% endblock %}
{% block title %}
    eBook APP About page
{% endblock %}

myapp/templates/myapp/detail0.html
{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#    <meta charset="UTF-8">#}
{#    <title>eBook App</title>#}
{#</head>#}
{#<body>#}
{#{% if booklist %}#}
{#        <h2></h2>Title</h2>#}
{#        <h2>Price</h2>#}
{#        <h2>Publisher</h2>#}
{#      </tr>#}
{# {% for book in booklist %}#}
{#        <h2>{{ booklist.title }}</h2>#}
{#        <h2>{{ booklist.price }}</h2>#}
{#        <h2>{{ booklist.publisher.name }}</h2>#}
{# {% endfor %}#}
{#{% endif %}#}
{#<!-- <p>#}
{#  <a href="/myapp19/index/">Go to Index Page</a>#}
{#</p> -->#}
{#    <a href="{% url 'myapp:index' %}">index</a>#}
{#</body>#}
{#</html>#}



<!DOCTYPE html>
<html lang="en">
<head>
</head>
<body>

<h3>{{book.title}}</h3>
<h4>{{book.publisher.name}}</h4>
<h4>${{book.price}}</h4>

<a href="{% url 'myapp:index' %}">Back to index</a>

</body>

</html>

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% include 'myapp/index0.html' %}
    {% block myhdg %}
    Hello Kesha
    {% endblock %}
{% endblock %}

myapp/templates/myapp/order_response.html
{% extends 'myapp/base.html' %}

{% block body_block %}
        <h2>Books in order</h2>
        <ol>
            {% for book  in books %}
                <li>
                        {{book.title}}
                </li>
            {% endfor %}
        </ol>

{% endblock %}

myapp/templates/myapp/placeorder.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<form action="{% url 'myapp:place_order' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
<input type="submit" name="submit1" value="Find Books" />
</form>

{% endblock %}

myapp/templates/myapp/register.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    <form action="{% url 'myapp:user_register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" name="submit1" value="Register" />
    </form>

{% endblock %}

myapp/templates/myapp/results.html
{% extends 'myapp/base.html' %}

{% block body_block %}
    {% if booklist %}
        <h2>List of Books</h2>
        <ol>
            {% for book  in booklist %}
                <li>
                        {{book.title}}
                </li>
            {% endfor %}
        </ol>

    {% endif %}
{% endblock %}

{% block myhdg %}
    Hello {{ name }}
    Category is {{ category }}
{% endblock %}

myapp/templates/myapp/review.html
{% extends 'myapp/base.html' %}

{% block body_block %}
<form action="{% url 'myapp:review' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
<input type="submit" name="submit" value="Find Books" />
</form>

{% endblock %}